// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANIH9-dNsml-V47g2kouofke9rKGPeZbs',
    appId: '1:1086808983934:web:b4a85875c293c803ec8b2f',
    messagingSenderId: '1086808983934',
    projectId: 'aishopper-1a194',
    authDomain: 'aishopper-1a194.firebaseapp.com',
    storageBucket: 'aishopper-1a194.firebasestorage.app',
    measurementId: 'G-E4XESRYHDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpok7ybuKfAGeroj69mEzKiajWPx8ETRM',
    appId: '1:1086808983934:android:cce03a9a3551837eec8b2f',
    messagingSenderId: '1086808983934',
    projectId: 'aishopper-1a194',
    storageBucket: 'aishopper-1a194.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY1DN3RH0rEvTynfNBaxhf0yaJA36gMow',
    appId: '1:1086808983934:ios:e38709d81ed48785ec8b2f',
    messagingSenderId: '1086808983934',
    projectId: 'aishopper-1a194',
    storageBucket: 'aishopper-1a194.firebasestorage.app',
    iosClientId: '1086808983934-1keav9skhvvpije2tphj3r8clh0hhdue.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiShopperOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY1DN3RH0rEvTynfNBaxhf0yaJA36gMow',
    appId: '1:1086808983934:ios:e38709d81ed48785ec8b2f',
    messagingSenderId: '1086808983934',
    projectId: 'aishopper-1a194',
    storageBucket: 'aishopper-1a194.firebasestorage.app',
    iosClientId: '1086808983934-1keav9skhvvpije2tphj3r8clh0hhdue.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiShopperOnline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANIH9-dNsml-V47g2kouofke9rKGPeZbs',
    appId: '1:1086808983934:web:3d03f1199700355dec8b2f',
    messagingSenderId: '1086808983934',
    projectId: 'aishopper-1a194',
    authDomain: 'aishopper-1a194.firebaseapp.com',
    storageBucket: 'aishopper-1a194.firebasestorage.app',
    measurementId: 'G-55DQDL6K7W',
  );
}
